services:
  r-scape:
    image: rscape:2.6.20

    command: starman --listen :3000 --workers 5 rscape.psgi
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - /opt/rscape/rscape-data:/tmp/rscape

    restart: unless-stopped
