services:
  r-scape:
    image: localhost/rscape:2.6.20

    environment:
      CATALYST_DEBUG: 1
    ports:
      - '8080:8080'
    volumes:
      - ./R-scape:/app
      - ./rscape-data:/tmp/rscape

    restart: unless-stopped
